@ECHO OFF
C:
CD \DOORS\LORD
ECHO **Seth Able's Node Data System, for NODE %1 >NODE%1.DAT
ECHO BBSNAME {YOUR BBS HERE} >>NODE%1.DAT
ECHO BBSTYPE DOORSYS >>NODE%1.DAT
ECHO COMPORT 1 >>NODE%1.DAT
ECHO ;FOSSIL >>NODE%1.DAT
ECHO LOCKBAUD 38400 >>NODE%1.DAT
ECHO STATUS ON >>NODE%1.DAT
ECHO STATFORE 3 >>NODE%1.DAT
ECHO STATBACK 7 >>NODE%1.DAT
ECHO ;COLOR1 >>NODE%1.DAT
ECHO NODIRECT >>NODE%1.DAT
ECHO ;UNUSED >>NODE%1.DAT
ECHO BBSDROP c:\NODEinfo\%1 >>NODE%1.DAT
ECHO ;UNUSED >>NODE%1.DAT
ECHO ;UNUSED >>NODE%1.DAT
ECHO ;UNUSED >>NODE%1.DAT
LORD %1 /DREW
exitemu
