#!/usr/bin/perl


sub lastcallers{
  if ($config{'lastcallenable'} ne "0") {
    $ctime = get_current_time();
    $cdate = get_current_date();
    if (-e "$config{'home'}$config{'text'}/lastcallers") {
      if (-e "$config{'home'}$config{'text'}/lastcalltop.$info{'ext'}") {
	writeline("\n");
        readfile("lastcalltop.$info{'ext'}");
      } else {
        writeline($theme{'lastcalltopa'},1);
        writeline($theme{'lastcalltopb'},1);
      }
      readfile("lastcallers");
      if (-e "$config{'home'}$config{'text'}/lastcallbot.$info{'ext'}") {
        readfile("lastcallbot.$info{'ext'}");
      } else {
        writeline($theme{'lastcallbot'});
      }
      unless ($_[0] =~/nopause/) {
        pause();
      }

    } else {
      writeline($theme{'lastcallemp'},1);
    }
      open (my $in_fh, '<', "$config{'home'}$config{'text'}/lastcallers");
        @lastcalls=<$in_fh>;
      close($in_fh);
      $lastkeep=$config{'lastcallers'};
      --$lastkeep;
      unless (scalar(@lastcalls) <= $lastkeep) {
        until (scalar(@lastcalls) <= $lastkeep || scalar(@lastcalls) <= 0) {
          $junk=shift(@lastcalls);
        }
      }
      $didcall=0;
      open (my $lc_fh, '>', "$config{'home'}$config{'text'}/lastcallers");
      foreach $caller(@lastcalls) {
        if ($caller=~/$info{'handle'}/i) {
          next;
        }
        print $lc_fh $caller;
      }
      close ($lc_fh);

      $ctime=$ctime;
      unless ($didcall eq 1) {
format lastcallers =
@<<<<<<< @<<<<<<<<<<<<<<<  .....  @<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
$ctime,$whouser,$whowhere
.
        writeline($config{'systemcolor'},1);
        open (lastcallers, '>>', "$config{'home'}$config{'text'}/lastcallers");
         $~="lastcallers";
         $whouser=$info{'handle'};
         $whowhere=$info{'location'};
         write lastcallers;
         $~="stdout";
        close (lastcallers);
      }
    }
  }
return 1;
