#!/usr/bin/perl
#
# User authentication module for PhotonBBS
#

# Helper to load modules
sub require_module {
    my ($mod) = @_;
    my $sys_path = "/opt/photonbbs/modules/$mod";
    my $local_path = "./modules/$mod";
    if (-e $sys_path) {
        require $sys_path unless $INC{$sys_path};
    } elsif (-e $local_path) {
        require $local_path unless $INC{$local_path};
    }
}

sub generate_salt {
  my @chars = ('A'..'Z', 'a'..'z', 0..9, '.', '/');
  return join '', map { $chars[rand @chars] } 1..16;
}

sub hash_password {
  my ($password) = @_;
  my $salt = '$5$' . generate_salt() . '$'; # $5$ = SHA-256
  return crypt($password, $salt);
}

sub check_password {
  my ($password, $stored_hash) = @_;
  return crypt($password, $stored_hash) eq $stored_hash;
}

sub authenticate {
  # SSH key authentication - user already verified by sshd
  if ($info{'proto'} eq "SSH" && $ENV{'PHOTONBBS_USER'}) {
    $info{'handle'} = $ENV{'PHOTONBBS_USER'};
    my $ucheck = finduser();
    if ($ucheck !~ /invalid/) {
      colorize();
      logger("NOTICE: $info{'handle'} authenticated via SSH key on node $info{'tty'} via $info{'connect'}");
      return;
    }
    # Key exists but user record gone - fall through to normal login
    $info{'handle'} = "";
    logger("WARN: SSH key user $ENV{'PHOTONBBS_USER'} not found in user database");
  }

  # Reduce the idle disconnect for sessions at the login prompt.
  $defaultidle=$config{'idledisconnect'};
  $config{'idledisconnect'}=90;
  login: {
    unless (defined($tries)) {
      $tries=1;
    } else {
      ++$tries;
    }
    if ($tries > $config{'authretries'}) {
      bye();
    }
    $fuser=$config{'home'}.$config{'data'}."/users.dat";
    unless ( -e "$fuser" ) {
      writeline($theme{'configfirstuser'});
      $config{'sec_user'} = $config{'sec_sysop'};
      $info{'handle'}="NEW";
    }
    unless ( -d "$config{'home'}$config{'data'}/users") {
      mkdir ("$config{'home'}$config{'data'}/users");
    }
    unless ($info{'handle'} ne "") {
      writeline($theme{'login'}." ");
      $info{'handle'}=getline(text,20);
      chomp ($info{'handle'});
      if ($info{'handle'} eq "") {
        $info{'handle'}="Unknown User";
      }
    }
    if ($info{'handle'} =~/[Nn][Ee][Ww]/) {
      newuser();
    }
    if ($firstlogon ne "1") {
      $ucheck=finduser();
      if ($ucheck =~/invalid/) {
        writeline($theme{'nouser'});
        $info{'handle'}="";
        goto login;
      }
      $tries="";
      colorize();
      testpasswd: {
          writeline($theme{'passwordprompt'}." ");
          $result=getline(password,$config{'passlength'});
          unless (check_password($result, $info{'password'})) {
            writeline($theme{'mismatch'});
            logger("WARN: ".$info{'handle'}." incorrect password on node ".$info{'tty'}." via ".$info{'connect'});
            
            # SECURITY: Record failed login attempt
            require_module("pb-security");
            my $banned = record_failed_login($info{'connect'}, $info{'handle'});
            
            unless (defined($tries)) {
              $tries=1;
            } else {
              ++$tries;
            }
            if ($tries eq 4 || $banned) {
              if ($banned) {
                writeline("@RED\n\nYour IP has been banned due to multiple failed login attempts.\n");
                writeline("Contact the system administrator if you believe this is an error.\n@RST");
                logger("SECURITY: IP ".$info{'connect'}." auto-banned after failed logins");
              }
              bye();
            }
            goto testpasswd;
          }
      }
    } else {
      writeline($theme{'fstwelcome'});
    }
    $result="";
    logger("NOTICE: ".$info{'handle'}." logged in on node ".$info{'tty'}." via ".$info{'connect'});
    $config{'idledisconnect'}=$defaultidle;
  }
}

sub getuname {
  $tochk=$_[0];
  $fuser=$config{'home'}.$config{'data'}."/users.dat";
  lockfile("$fuser");
  open (my $uname_fh, '<', $fuser);
  while (<$uname_fh>) {
    $line=$_;
    chomp ($line);
    ($chkid,$chkname)=split(/\|/,$line);
    if ($chkid eq $tochk) {
      last;
    }
  }
  close ($uname_fh);
  unlockfile("$fuser");
  return "$chkname";
}

sub finduser {
  $tochk=$_[0];
  if ($tochk eq "") {
    $tochk=$info{'handle'};
  }
  $fuser=$config{'home'}.$config{'data'}."/users.dat";
  if ( -e "$fuser" ) {
    lockfile("$fuser");
    open (my $user_fh, '<', $fuser);
    while (<$user_fh>) {
      $line=$_;
      chomp ($line);
      ($chkid,$chkname)=split(/\|/,$line);
      if ($chkname eq $tochk) {
        close ($user_fh);
        unlockfile("$fuser");
        loaduser($chkid);
        return "valid";
      }
    }
    close ($user_fh);
    unlockfile("$fuser");
  }
  return "invalid";
}

sub finduserid {
  my $handle = $_[0] // $info{'handle'};
  $fuser = $config{'home'} . $config{'data'} . "/users.dat";
  if (-e "$fuser") {
    lockfile("$fuser");
    open(my $in, "<", $fuser);
    while (<$in>) {
      chomp;
      my ($chkid, $chkname) = split(/\|/, $_);
      if ($chkname eq $handle) {
        close($in);
        unlockfile("$fuser");
        return $chkid;
      }
    }
    close($in);
    unlockfile("$fuser");
  }
  return "0";
}

sub loaduser {
  $ruser=$config{'home'}.$config{'data'}."/users/".$_[0].".dat";
  lockfile("$ruser");
  open (my $load_fh, '<', $ruser);
  while (<$load_fh>) {
    $line=$_;
    chomp $line;
    unless ($line =~/^#/) {
      if ($line =~/#/i) {
        ($newline,$junk)=split(/#/,$line);
        while ($newline =~/\s$/) {
          chop $newline;
        }
        $line=$newline;
      }
      ($key,$value)=split(/=/,$line);
      unless ($key =~/node/ || $key =~/connect/){
        $info{$key}=$value;
      } else {
        $info{'lastnode'}=$value;
      }
    }
  }
  close ($load_fh);
  unlockfile("$ruser");
  if ($info{'ansi'} eq 0) {
    $info{'ext'}="asc";
  } else {
    $info{'ext'}="ans";
  }
  colorize();
}

sub updateuser {
  unless (defined($info{'id'}) && $info{'id'} ne "" && $info{'id'} ne "0") {
    # Assign next available user ID
    my $maxid = 0;
    my $fuser = $config{'home'} . $config{'data'} . "/users.dat";
    if (-e $fuser) {
      lockfile($fuser);
      open(my $in, "<", $fuser);
      while (<$in>) {
        chomp;
        my ($chkid, $chkname) = split(/\|/, $_);
        $maxid = $chkid if ($chkid =~ /^\d+$/ && $chkid > $maxid);
      }
      close($in);
      unlockfile($fuser);
    }
    $info{'id'} = $maxid + 1;
    # Append to users.dat
    my $outto = $fuser;
    lockfile($outto);
    open(my $out, ">>", $outto);
    print $out $info{'id'} . "|" . $info{'handle'} . "\n";
    close($out);
    unlockfile($outto);
  }
  my $outto = $config{'home'} . $config{'data'} . "/users/" . $info{'id'} . ".dat";
  lockfile($outto);
  open(my $out, ">", $outto);
  foreach my $key (keys %info) {
    unless ($key =~ /proto/) {
      print $out $key . "=" . $info{$key} . "\n";
    }
  }
  logger("NOTICE: Saved " . $info{'handle'} . " to record number " . $info{'id'});
  close($out);
  unlockfile($outto);
}

sub newuser {
  if ($config{'public'} eq "0") {
    writeline($theme{'nonewusers'});
    bye();
  }
  logger("NOTICE: New user on Node ".$info{'tty'});
  iamat("New User", "Creating an account");
  $readit = 0;
  if (-e $info{'home'}."/".$info{'text'}."/welcome.txt") {
    readfile($info{'home'}."/".$info{'text'}."/welcome.txt");
    $readit = 1;
  }
  if (-e $info{'home'}."/".$info{'text'}."/welcome".$info{'ext'} && $readit ne 1) {
    readfile($info{'home'}."/".$info{'text'}."/welcome".$info{'ext'});
    $readit = 1;
  }
  if ($readit eq 1) {
    writeline($theme{'agreeprompt'});
    $result=waitkey("N");
    unless ($result =~/[Yy]/) {
      $noevents=1;
      writeline($theme{'noagree'});
      $noevents="";
      bye();
    }
  }
  $readit="";
  writeline($theme{'newprompta'});
  writeline($theme{'ansiprompt'}." ");
  $noevents=1;
  $result=waitkey("Y");
  $noevents="";
  if ($result =~/[Yy]/) {
    $info{'ansi'}=1;
  } else {
    $info{'ansi'}=0;
  }

  colorize();
  applytheme($config{'theme'});

  #writeline("How many columns is your display (40/80)? ");
  #my $cols = getline(text,3,"80",1);
  #chomp($cols);
  #if ($cols =~ /^40$/i) {
  #  $info{'terminal_width'} = 40;
  #} else {
    $info{'terminal_width'} = 80;  # Default
  #}

  if ($config{'usefullname'} eq "1") {
    fullname: {
      writeline($theme{'fullname'}." ");
      $info{'rname'}=getline(text,50,"",1);
      unless ($info{'rname'} =~/\s/i) {
        writeline($theme{'fullnwrong'});
        goto fullname;
      }
    }
  }
  if ($config{'usephonenum'} eq "1") {
    phonenumber: {
      writeline($theme{'phoneprompt'});
      $info{'phonenumber'}=getline(phone,14,"",1);
    }
  }
  writeline($theme{'locationprompt'}." ");
  $info{'location'}=getline(text,50,"",1);
  email: {
    writeline($theme{'setemaila'}." ");
    $info{'email'}=getline(text,40,"",1);
    unless ($info{'email'} =~/\@/i && $info{'email'} =~/\./i) {
      goto email;
    }
  }
  writeline($theme{'dobprompt'}." ");
  $info{'dob'}=getline(dob,10,"",1);
  newid: {
    writeline($theme{'useridprompt'}." ");
    $info{'handle'}=getline(text,16,"",1);
    chomp ($info{'handle'});
    $handletest=uc($info{'handle'});
    if ($handletest =~/New/gi) {
      $test=" ";
    }
    unless ($handletest =~/\w/i) {
      $test="valid";
    } else {
      $test=finduser($info{'handle'});
    }
    until ($test =~/invalid/i) {
      writeline($theme{'usedidprompt'});
      writeline($theme{'useridprompt'}." ");
      $info{'handle'}=getline(text,16,"",1);
      $handletest=uc($info{'handle'});
      if ($handletest =~/New/gi) {
        $test=" ";
      }
      unless ($handletest =~/\w/i) {
        $test="valid";
      } else {
        $test=finduser($info{'handle'});
      }
     }
  }
  applytheme($config{'theme'});
  writeline($theme{'idokprompt'}." ");
  $result=waitkey("Y");
  unless ($result =~/[Yy]/) {
    writeline("\n");
    goto newid;
  }
  setpassword: {
    writeline($theme{'setpassword'}.$theme{'setpasswordb'}." ");
    $passa=getline(password,$config{'passlength'},"",1);
    if (!defined($passa) || $passa eq "") {
      writeline($theme{'passblank'} // "Password cannot be blank. Please enter a password.");
      goto setpassword;
    }
    writeline($theme{'setpasswordc'}." ");
    $passb=getline(password,$config{'passlength'},"",1);
    if ($passa ne $passb) {
      writeline($theme{'passmatch'});
      goto setpassword;
    }
    if (!defined($passb) || $passb eq "") {
      writeline($theme{'passblank'} // "Password cannot be blank. Please enter a password.");
      goto setpassword;
    }
    $info{'password'}=hash_password($passa);
  }
  if ( $info{'id'} == 1 ) {
    $info{'security'}=$config{'sec_sysop'};
  } else {
    $info{'security'}=$config{'sec_user'};
  }
  $info{'theme'}=$config{'deftheme'};;
  $info{'dnd'}="0";
  writeline($theme{'remember'});
  $null=waitkey();
  updateuser();
  
  # Re-initialize terminal config to pick up the saved width
  initialize_terminal_config();

  # Register the new user as online
  iamat($info{'handle'}, "Logging in");
  writeline($theme{'goodbyemsg'} . $RST, 1);
  $firstlogon=1;
}

sub chansi {
  writeline($theme{'ansiprompt'} . " ");
  $noevents = 1;
  $result = waitkey("Y");
  $noevents = "";
  if ($result =~ /[Yy]/) {
    $info{'ansi'} = 1;
    $info{'ext'} = "ans";
  } else {
    $info{'ansi'} = 0;
    $info{'ext'} = "asc";
  }
  updateuser();
  colorize();
  applytheme($config{'theme'});
}

sub chbanned {
  writeline($theme{'banprompt'} . " ");
  $noevents = 1;
  $result = waitkey("N");
  $noevents = "";
  if ($result =~ /[Yy]/) {
    $info{'banned'} = "Y";
  } else {
    $info{'banned'} = "N";
  }
  updateuser();
  colorize();
  applytheme($config{'theme'});
}

sub chhide {
  if ($info{'proto'} eq "SSH" && $info{'hidden'} ne "Y") {
    writeline($WHT."Sorry, only SSH users can go invisible.",1);
    return;
  }
  if ($info{'hidden'} eq "Y") {
    writeline($WHT."You are no longer invisible.",1);
    $info{'hidden'}="N";
  } else {
    writeline($WHT."You are now invisible.",1);
    $info{'hidden'}="Y";
  }

  iamat($info{'handle'},"Chat");

  if (-e "$config{'home'}$config{'messages'}/teleconf/TELEPUB_/$info{'node'}") {
    lockfile("$config{'home'}$config{'messages'}/teleconf/TELEPUB_/$info{'node'}");
    open (my $hide_fh, '>', "$config{'home'}$config{'messages'}/teleconf/TELEPUB_/$info{'node'}");
    unless ($info{'hidden'} eq "Y") {
     print $hide_fh $info{'node'}."|".$info{'handle'}."|".$channel."\n";
    } else {
     print $hide_fh $info{'node'}."|*** HIDDEN ***|".$channel."\n";
    }
    close ($hide_fh);
    unlockfile("$config{'home'}$config{'messages'}/teleconf/TELEPUB_/$info{'node'}");
  }
  updateuser();
}

sub chphone {
  writeline($theme{'phoneprompt'});
  $info{'phonenumber'}=getline(phone,14,"",1);
  updateuser();
}

sub chdob {
  writeline($theme{'dobprompt'});
  $info{'dob'}=getline(dob,10,"",1);
  updateuser();
}

sub chrealname {
  fullname: {
    writeline($theme{'fullname'});
    $info{'rname'}=getline(text,50,"",1);
    unless ($info{'rname'} =~/\s/i) {
      writeline($theme{'fullnwrong'});
      goto fullname;
    }
  }
  updateuser();
}

sub chpassword {
  setpassword: {
    writeline($theme{'setpassword'}.$theme{'setpasswordb'}." ");
    $passa=getline(password,$config{'passlength'},"",1);
    if (!defined($passa) || $passa eq "") {
      writeline($theme{'passblank'} // "Password cannot be blank. Please enter a password.");
      goto setpassword;
    }
    writeline($theme{'setpasswordc'}." ");
    $passb=getline(password,$config{'passlength'},"",1);
    if ($passa ne $passb) {
      writeline($theme{'passmatch'});
      goto setpassword;
    }
    if (!defined($passb) || $passb eq "") {
      writeline($theme{'passblank'} // "Password cannot be blank. Please enter a password.");
      goto setpassword;
    }
    $info{'password'}=hash_password($passa);
  }
  updateuser();
}

sub chlocal {
  writeline($theme{'locationprompt'});
  $info{'location'}=getline(text,50,"",1);
  updateuser();
}

sub chdnd {
  unless ($info{'dnd'} eq "1") {
    writeline($LGN."Do not disturb is now ".$YLW."ON".$LGN."\nIt will not be disabled until ".$RED."YOU".$LGN." turn it off",1);
    $info{'dnd'}="1";
  } else {
    writeline($LGN."Do not disturb is now ".$YLW."OFF".$LGN."\nIt will be disabled until ".$RED."YOU".$LGN." turn it on",1);
    $info{'dnd'}="0";
  }
  updateuser();
}

sub chemail {
  writeline($theme{'setemaila'});
  $info{'email'}=getline(text,40,"",1);
  updateuser();
}

# ============================================================================
# SSH KEY MANAGEMENT
# ============================================================================

# Valid SSH key type prefixes
my @VALID_KEY_TYPES = (
    'ssh-rsa',
    'ssh-ed25519',
    'ssh-ed448',
    'ssh-dss',
    'ecdsa-sha2-nistp256',
    'ecdsa-sha2-nistp384',
    'ecdsa-sha2-nistp521',
    'sk-ssh-ed25519@openssh.com',
    'sk-ecdsa-sha2-nistp256@openssh.com',
);

sub validate_ssh_key {
    my ($key) = @_;
    return 0 unless defined $key && length($key) > 20;

    # Must be a single line
    return 0 if $key =~ /\n/;

    # Must start with a valid key type
    my $valid_type = 0;
    for my $type (@VALID_KEY_TYPES) {
        if ($key =~ /^\Q$type\E\s/) {
            $valid_type = 1;
            last;
        }
    }
    return 0 unless $valid_type;

    # Key data should be base64 (second field)
    my @parts = split(/\s+/, $key);
    return 0 unless scalar(@parts) >= 2;
    return 0 unless $parts[1] =~ /^[A-Za-z0-9+\/=]+$/;
    return 0 unless length($parts[1]) >= 16;

    # Reasonable length limit (16KB should cover any key type)
    return 0 if length($key) > 16384;

    return 1;
}

sub chsshkey {
    my ($subcmd) = @_;

    # /set sshkey remove
    if (defined $subcmd && $subcmd =~ /^remove$/i) {
        if (!$info{'sshkey'} || $info{'sshkey'} eq '') {
            writeline($config{'systemcolor'} . "No SSH key configured." . $RST, 1);
            return;
        }
        $info{'sshkey'} = '';
        updateuser();
        rebuild_authorized_keys();
        writeline($config{'systemcolor'} . "SSH key removed." . $RST, 1);
        logger("NOTICE: $info{'handle'} removed their SSH key");
        return;
    }

    # Show current key if set
    if ($info{'sshkey'} && $info{'sshkey'} ne '') {
        my $keytype = (split(/\s+/, $info{'sshkey'}))[0];
        my $keydata = (split(/\s+/, $info{'sshkey'}))[1];
        my $fingerprint = substr($keydata, 0, 12) . "..." . substr($keydata, -8);
        writeline($config{'datacolor'} . "Current key: " .
                  $config{'usercolor'} . $keytype . " " . $fingerprint . $RST, 1);
        writeline("", 1);
    }

    writeline($config{'themecolor'} . "Paste your SSH public key (from ~/.ssh/id_*.pub):" . $RST, 1);
    writeline($config{'systemcolor'} . "Or press Enter to cancel." . $RST, 1);
    writeline($config{'promptcolor'} . "> " . $RST);

    my $key = getline('text', 2048, "", 1);
    $key =~ s/^\s+|\s+$//g if defined $key;

    if (!defined $key || $key eq '') {
        writeline($config{'systemcolor'} . "Cancelled." . $RST, 1);
        return;
    }

    unless (validate_ssh_key($key)) {
        writeline($config{'errorcolor'} . "Invalid SSH public key format." . $RST, 1);
        writeline($config{'systemcolor'} . "Key must start with ssh-rsa, ssh-ed25519, ecdsa-sha2-*, etc." . $RST, 1);
        return;
    }

    $info{'sshkey'} = $key;
    updateuser();
    rebuild_authorized_keys();

    my $keytype = (split(/\s+/, $key))[0];
    writeline($config{'systemcolor'} . "SSH key saved (" .
              $config{'usercolor'} . $keytype . $config{'systemcolor'} . ")." . $RST, 1);
    writeline($config{'datacolor'} . "You can now SSH to this BBS." . $RST, 1);
    logger("NOTICE: $info{'handle'} set SSH key ($keytype)");
}

sub rebuild_authorized_keys {
    my $auth_keys_dir  = "/home/bbs/.ssh";
    my $auth_keys_file = "$auth_keys_dir/authorized_keys";
    my $users_dir      = $config{'home'} . $config{'data'} . "/users";

    # Bail if SSH is not enabled (no /home/bbs/.ssh directory)
    return unless -d $auth_keys_dir;

    my @lines;
    my $forced_opts = 'command="/opt/photonbbs/sbin/photonbbs-client SSH",' .
                      'no-port-forwarding,no-X11-forwarding,no-agent-forwarding';

    # Scan all user data files for sshkey entries
    if (opendir(my $dh, $users_dir)) {
        while (my $file = readdir($dh)) {
            next unless $file =~ /^\d+\.dat$/;
            my $path = "$users_dir/$file";
            if (open(my $fh, '<', $path)) {
                my $handle = '';
                my $sshkey = '';
                while (my $line = <$fh>) {
                    chomp $line;
                    if ($line =~ /^handle=(.+)/) {
                        $handle = $1;
                    } elsif ($line =~ /^sshkey=(.+)/) {
                        $sshkey = $1;
                    }
                }
                close($fh);
                if ($sshkey ne '' && validate_ssh_key($sshkey)) {
                    # environment="PHOTONBBS_USER=handle" lets the client
                    # identify which BBS user is connecting
                    push @lines, "environment=\"PHOTONBBS_USER=$handle\",$forced_opts $sshkey";
                }
            }
        }
        closedir($dh);
    }

    # Atomic write
    my $tmp = "$auth_keys_file.tmp.$$";
    if (open(my $fh, '>', $tmp)) {
        for my $line (@lines) {
            print $fh "$line\n";
        }
        close($fh);
        chmod(0600, $tmp);
        rename($tmp, $auth_keys_file);
        # Ensure ownership (bbs user)
        my ($uid, $gid) = (getpwnam('bbs'))[2,3];
        chown($uid, $gid, $auth_keys_file) if defined $uid;
    }
}

return 1;
