#!/usr/bin/perl
#
# User authentication module for PhotonBBS
#

# Helper to load modules
sub require_module {
    my ($mod) = @_;
    my $sys_path = "/opt/photonbbs/modules/$mod";
    my $local_path = "./modules/$mod";
    if (-e $sys_path) {
        require $sys_path unless $INC{$sys_path};
    } elsif (-e $local_path) {
        require $local_path unless $INC{$local_path};
    }
}

sub generate_salt {
  my @chars = ('A'..'Z', 'a'..'z', 0..9, '.', '/');
  return join '', map { $chars[rand @chars] } 1..16;
}

sub hash_password {
  my ($password) = @_;
  my $salt = '$5$' . generate_salt() . '$'; # $5$ = SHA-256
  return crypt($password, $salt);
}

sub check_password {
  my ($password, $stored_hash) = @_;
  return crypt($password, $stored_hash) eq $stored_hash;
}

sub authenticate {
  # Reduce the idle disconnect for sessions at the login prompt.
  $defaultidle=$config{'idledisconnect'};
  $config{'idledisconnect'}=90;
  login: {
    unless (defined($tries)) {
      $tries=1;
    } else {
      ++$tries;
    }
    if ($tries > $config{'authretries'}) {
      bye();
    }
    $fuser=$config{'home'}.$config{'data'}."/users.dat";
    unless ( -e "$fuser" ) {
      writeline($theme{'configfirstuser'});
      $config{'sec_user'} = $config{'sec_sysop'};
      $info{'handle'}="NEW";
    }
    unless ( -d "$config{'home'}$config{'data'}/users") {
      mkdir ("$config{'home'}$config{'data'}/users");
    }
    unless ($info{'handle'} ne "") {
      writeline($theme{'login'}." ");
      $info{'handle'}=getline(text,20);
      chomp ($info{'handle'});
      if ($info{'handle'} eq "") {
        $info{'handle'}="Unknown User";
      }
    }
    if ($info{'handle'} =~/[Nn][Ee][Ww]/) {
      newuser();
    }
    if ($firstlogon ne "1") {
      $ucheck=finduser();
      if ($ucheck =~/invalid/) {
        writeline($theme{'nouser'});
        $info{'handle'}="";
        goto login;
      }
      $tries="";
      colorize();
      testpasswd: {
          writeline($theme{'passwordprompt'}." ");
          $result=getline(password,$config{'passlength'});
          unless (check_password($result, $info{'password'})) {
            writeline($theme{'mismatch'});
            logger("WARN: ".$info{'handle'}." incorrect password on node ".$info{'tty'}." via ".$info{'connect'});
            
            # SECURITY: Record failed login attempt
            require_module("pb-security");
            my $banned = record_failed_login($info{'connect'}, $info{'handle'});
            
            unless (defined($tries)) {
              $tries=1;
            } else {
              ++$tries;
            }
            if ($tries eq 4 || $banned) {
              if ($banned) {
                writeline("@RED\n\nYour IP has been banned due to multiple failed login attempts.\n");
                writeline("Contact the system administrator if you believe this is an error.\n@RST");
                logger("SECURITY: IP ".$info{'connect'}." auto-banned after failed logins");
              }
              bye();
            }
            goto testpasswd;
          }
      }
    } else {
      writeline($theme{'fstwelcome'});
    }
    $result="";
    logger("NOTICE: ".$info{'handle'}." logged in on node ".$info{'tty'}." via ".$info{'connect'});
    $config{'idledisconnect'}=$defaultidle;
  }
}

sub getuname {
  $tochk=$_[0];
  $fuser=$config{'home'}.$config{'data'}."/users.dat";
  lockfile("$fuser");
  open (my $uname_fh, '<', $fuser);
  while (<$uname_fh>) {
    $line=$_;
    chomp ($line);
    ($chkid,$chkname)=split(/\|/,$line);
    if ($chkid eq $tochk) {
      last;
    }
  }
  close ($uname_fh);
  unlockfile("$fuser");
  return "$chkname";
}

sub finduser {
  $tochk=$_[0];
  if ($tochk eq "") {
    $tochk=$info{'handle'};
  }
  $fuser=$config{'home'}.$config{'data'}."/users.dat";
  if ( -e "$fuser" ) {
    lockfile("$fuser");
    open (my $user_fh, '<', $fuser);
    while (<$user_fh>) {
      $line=$_;
      chomp ($line);
      ($chkid,$chkname)=split(/\|/,$line);
      if ($chkname eq $tochk) {
        close ($user_fh);
        unlockfile("$fuser");
        loaduser($chkid);
        return "valid";
      }
    }
    close ($user_fh);
    unlockfile("$fuser");
  }
  return "invalid";
}

sub finduserid {
  my $handle = $_[0] // $info{'handle'};
  $fuser = $config{'home'} . $config{'data'} . "/users.dat";
  if (-e "$fuser") {
    lockfile("$fuser");
    open(my $in, "<", $fuser);
    while (<$in>) {
      chomp;
      my ($chkid, $chkname) = split(/\|/, $_);
      if ($chkname eq $handle) {
        close($in);
        unlockfile("$fuser");
        return $chkid;
      }
    }
    close($in);
    unlockfile("$fuser");
  }
  return "0";
}

sub loaduser {
  $ruser=$config{'home'}.$config{'data'}."/users/".$_[0].".dat";
  lockfile("$ruser");
  open (my $load_fh, '<', $ruser);
  while (<$load_fh>) {
    $line=$_;
    chomp $line;
    unless ($line =~/^#/) {
      if ($line =~/#/i) {
        ($newline,$junk)=split(/#/,$line);
        while ($newline =~/\s$/) {
          chop $newline;
        }
        $line=$newline;
      }
      ($key,$value)=split(/=/,$line);
      unless ($key =~/node/ || $key =~/connect/){
        $info{$key}=$value;
      } else {
        $info{'lastnode'}=$value;
      }
    }
  }
  close ($load_fh);
  unlockfile("$ruser");
  if ($info{'ansi'} eq 0) {
    $info{'ext'}="asc";
  } else {
    $info{'ext'}="ans";
  }
  colorize();
}

sub updateuser {
  unless (defined($info{'id'}) && $info{'id'} ne "" && $info{'id'} ne "0") {
    # Assign next available user ID
    my $maxid = 0;
    my $fuser = $config{'home'} . $config{'data'} . "/users.dat";
    if (-e $fuser) {
      lockfile($fuser);
      open(my $in, "<", $fuser);
      while (<$in>) {
        chomp;
        my ($chkid, $chkname) = split(/\|/, $_);
        $maxid = $chkid if ($chkid =~ /^\d+$/ && $chkid > $maxid);
      }
      close($in);
      unlockfile($fuser);
    }
    $info{'id'} = $maxid + 1;
    # Append to users.dat
    my $outto = $fuser;
    lockfile($outto);
    open(my $out, ">>", $outto);
    print $out $info{'id'} . "|" . $info{'handle'} . "\n";
    close($out);
    unlockfile($outto);
  }
  my $outto = $config{'home'} . $config{'data'} . "/users/" . $info{'id'} . ".dat";
  lockfile($outto);
  open(my $out, ">", $outto);
  foreach my $key (keys %info) {
    unless ($key =~ /proto/) {
      print $out $key . "=" . $info{$key} . "\n";
    }
  }
  logger("NOTICE: Saved " . $info{'handle'} . " to record number " . $info{'id'});
  close($out);
  unlockfile($outto);
}

sub newuser {
  if ($config{'public'} eq "0") {
    writeline($theme{'nonewusers'});
    bye();
  }
  logger("NOTICE: New user on Node ".$info{'tty'});
  iamat("New User", "Creating an account");
  $readit = 0;
  if (-e $info{'home'}."/".$info{'text'}."/welcome.txt") {
    readfile($info{'home'}."/".$info{'text'}."/welcome.txt");
    $readit = 1;
  }
  if (-e $info{'home'}."/".$info{'text'}."/welcome".$info{'ext'} && $readit ne 1) {
    readfile($info{'home'}."/".$info{'text'}."/welcome".$info{'ext'});
    $readit = 1;
  }
  if ($readit eq 1) {
    writeline($theme{'agreeprompt'});
    $result=waitkey("N");
    unless ($result =~/[Yy]/) {
      $noevents=1;
      writeline($theme{'noagree'});
      $noevents="";
      bye();
    }
  }
  $readit="";
  writeline($theme{'newprompta'});
  writeline($theme{'ansiprompt'}." ");
  $noevents=1;
  $result=waitkey("Y");
  $noevents="";
  if ($result =~/[Yy]/) {
    $info{'ansi'}=1;
  } else {
    $info{'ansi'}=0;
  }

  colorize();
  applytheme($config{'theme'});

  #writeline("How many columns is your display (40/80)? ");
  #my $cols = getline(text,3,"80",1);
  #chomp($cols);
  #if ($cols =~ /^40$/i) {
  #  $info{'terminal_width'} = 40;
  #} else {
    $info{'terminal_width'} = 80;  # Default
  #}

  if ($config{'usefullname'} eq "1") {
    fullname: {
      writeline($theme{'fullname'}." ");
      $info{'rname'}=getline(text,50,"",1);
      unless ($info{'rname'} =~/\s/i) {
        writeline($theme{'fullnwrong'});
        goto fullname;
      }
    }
  }
  if ($config{'usephonenum'} eq "1") {
    phonenumber: {
      writeline($theme{'phoneprompt'});
      $info{'phonenumber'}=getline(phone,14,"",1);
    }
  }
  writeline($theme{'locationprompt'}." ");
  $info{'location'}=getline(text,50,"",1);
  email: {
    writeline($theme{'setemaila'}." ");
    $info{'email'}=getline(text,40,"",1);
    unless ($info{'email'} =~/\@/i && $info{'email'} =~/\./i) {
      goto email;
    }
  }
  writeline($theme{'dobprompt'}." ");
  $info{'dob'}=getline(dob,10,"",1);
  newid: {
    writeline($theme{'useridprompt'}." ");
    $info{'handle'}=getline(text,16,"",1);
    chomp ($info{'handle'});
    $handletest=uc($info{'handle'});
    if ($handletest =~/New/gi) {
      $test=" ";
    }
    unless ($handletest =~/\w/i) {
      $test="valid";
    } else {
      $test=finduser($info{'handle'});
    }
    until ($test =~/invalid/i) {
      writeline($theme{'usedidprompt'});
      writeline($theme{'useridprompt'}." ");
      $info{'handle'}=getline(text,16,"",1);
      $handletest=uc($info{'handle'});
      if ($handletest =~/New/gi) {
        $test=" ";
      }
      unless ($handletest =~/\w/i) {
        $test="valid";
      } else {
        $test=finduser($info{'handle'});
      }
     }
  }
  applytheme($config{'theme'});
  writeline($theme{'idokprompt'}." ");
  $result=waitkey("Y");
  unless ($result =~/[Yy]/) {
    writeline("\n");
    goto newid;
  }
  setpassword: {
    writeline($theme{'setpassword'}.$theme{'setpasswordb'}." ");
    $passa=getline(password,$config{'passlength'},"",1);
    if (!defined($passa) || $passa eq "") {
      writeline($theme{'passblank'} // "Password cannot be blank. Please enter a password.");
      goto setpassword;
    }
    writeline($theme{'setpasswordc'}." ");
    $passb=getline(password,$config{'passlength'},"",1);
    if ($passa ne $passb) {
      writeline($theme{'passmatch'});
      goto setpassword;
    }
    if (!defined($passb) || $passb eq "") {
      writeline($theme{'passblank'} // "Password cannot be blank. Please enter a password.");
      goto setpassword;
    }
    $info{'password'}=hash_password($passa);
  }
  if ( $info{'id'} == 1 ) {
    $info{'security'}=$config{'sec_sysop'};
  } else {
    $info{'security'}=$config{'sec_user'};
  }
  $info{'theme'}=$config{'deftheme'};;
  $info{'dnd'}="0";
  writeline($theme{'remember'});
  $null=waitkey();
  updateuser();
  
  # Re-initialize terminal config to pick up the saved width
  initialize_terminal_config();

  # Register the new user as online
  iamat($info{'handle'}, "Logging in");
  writeline($theme{'goodbyemsg'} . $RST, 1);
  $firstlogon=1;
}

sub chansi {
  writeline($theme{'ansiprompt'} . " ");
  $noevents = 1;
  $result = waitkey("Y");
  $noevents = "";
  if ($result =~ /[Yy]/) {
    $info{'ansi'} = 1;
    $info{'ext'} = "ans";
  } else {
    $info{'ansi'} = 0;
    $info{'ext'} = "asc";
  }
  updateuser();
  colorize();
  applytheme($config{'theme'});
}

sub chbanned {
  writeline($theme{'banprompt'} . " ");
  $noevents = 1;
  $result = waitkey("N");
  $noevents = "";
  if ($result =~ /[Yy]/) {
    $info{'banned'} = "Y";
  } else {
    $info{'banned'} = "N";
  }
  updateuser();
  colorize();
  applytheme($config{'theme'});
}

sub chhide {
  if ($info{'proto'} eq "SSH" && $info{'hidden'} ne "Y") {
    writeline($WHT."Sorry, only SSH users can go invisible.",1);
    return;
  }
  if ($info{'hidden'} eq "Y") {
    writeline($WHT."You are no longer invisible.",1);
    $info{'hidden'}="N";
  } else {
    writeline($WHT."You are now invisible.",1);
    $info{'hidden'}="Y";
  }

  iamat($info{'handle'},"Chat");

  if (-e "$config{'home'}$config{'messages'}/teleconf/TELEPUB_/$info{'node'}") {
    lockfile("$config{'home'}$config{'messages'}/teleconf/TELEPUB_/$info{'node'}");
    open (my $hide_fh, '>', "$config{'home'}$config{'messages'}/teleconf/TELEPUB_/$info{'node'}");
    unless ($info{'hidden'} eq "Y") {
     print $hide_fh $info{'node'}."|".$info{'handle'}."|".$channel."\n";
    } else {
     print $hide_fh $info{'node'}."|*** HIDDEN ***|".$channel."\n";
    }
    close ($hide_fh);
    unlockfile("$config{'home'}$config{'messages'}/teleconf/TELEPUB_/$info{'node'}");
  }
  updateuser();
}

sub chphone {
  writeline($theme{'phoneprompt'});
  $info{'phonenumber'}=getline(phone,14,"",1);
  updateuser();
}

sub chdob {
  writeline($theme{'dobprompt'});
  $info{'dob'}=getline(dob,10,"",1);
  updateuser();
}

sub chrealname {
  fullname: {
    writeline($theme{'fullname'});
    $info{'rname'}=getline(text,50,"",1);
    unless ($info{'rname'} =~/\s/i) {
      writeline($theme{'fullnwrong'});
      goto fullname;
    }
  }
  updateuser();
}

sub chpassword {
  setpassword: {
    writeline($theme{'setpassword'}.$theme{'setpasswordb'}." ");
    $passa=getline(password,$config{'passlength'},"",1);
    if (!defined($passa) || $passa eq "") {
      writeline($theme{'passblank'} // "Password cannot be blank. Please enter a password.");
      goto setpassword;
    }
    writeline($theme{'setpasswordc'}." ");
    $passb=getline(password,$config{'passlength'},"",1);
    if ($passa ne $passb) {
      writeline($theme{'passmatch'});
      goto setpassword;
    }
    if (!defined($passb) || $passb eq "") {
      writeline($theme{'passblank'} // "Password cannot be blank. Please enter a password.");
      goto setpassword;
    }
    $info{'password'}=hash_password($passa);
  }
  updateuser();
}

sub chlocal {
  writeline($theme{'locationprompt'});
  $info{'location'}=getline(text,50,"",1);
  updateuser();
}

sub chdnd {
  unless ($info{'dnd'} eq "1") {
    writeline($LGN."Do not disturb is now ".$YLW."ON".$LGN."\nIt will not be disabled until ".$RED."YOU".$LGN." turn it off",1);
    $info{'dnd'}="1";
  } else {
    writeline($LGN."Do not disturb is now ".$YLW."OFF".$LGN."\nIt will be disabled until ".$RED."YOU".$LGN." turn it on",1);
    $info{'dnd'}="0";
  }
  updateuser();
}

sub chemail {
  writeline($theme{'setemaila'});
  $info{'email'}=getline(text,40,"",1);
  updateuser();
}

return 1;
