#!/bin/bash


###
### Not optimal, but necessary.
###

service crond start
service rsyslog start
service fail2ban start

###
### Intercept other commands.
###

if [ "$*" ]
then
  $*
  exit 0
fi

###
### Set up the PhotonBBS data files to be persistent.
###

if [ ! -e '/appdata/.installed' ]
then
  rsync -av /opt/photonbbs/data/* /appdata
  touch /appdata/.installed
fi
chown -R bbs:bbs /appdata

while [ true ]
do
  xinetd -dontfork
  sleep 1
done
