#!/bin/bash

###
### Not optimal, but necessary.
###

service crond start >/dev/null 2>&1
service rsyslog start >/dev/null 2>&1
service fail2ban start >/dev/null 2>&1

###
### Set up the PhotonBBS data files to be persistent.
###

if [ ! -e '/appdata/.installed' ]
then
  rsync -av /opt/photonbbs/data/* /appdata
  rm -rf /opt/photonbbs/sbin
  ln -s /appdata/sbin /opt/photonbbs
  rm -rf /opt/photonbbs/doors
  ln -s /appdata/doors /opt/photonbbs
  rm -rf /opt/photonbbs/data
  touch /appdata/.installed
fi

###
### Dosemu
###

if [ ! -e '/appdata/.dosemu/drive_c' ]
then
  mkdir -p /appdata/.dosemu/drive_c
fi

if [ ! -e '/appdata/.dosemu/drives' ]
then
  mkdir -p /appdata/.dosemu/drives
fi

ln -s /usr/share/dosemu/drive_z /appdata/.dosemu/drives/d 2>/dev/null
ln -s /appdata/.dosemu/drive_c /appdata/.dosemu/drives/c 2>/dev/null
ln -s /appdata/.dosemu /opt/photonbbs

ln -s /appdata /opt/photonbbs 2>/dev/null

###
### Move /etc/default/photonbbs to /appdata
###

if [ ! -e "/etc/default/photonbbs" ]
then
  mkdir /appdata/default
  mv /etc/default/photonbbs /appdata/default
  ln -s /appdata/default/photonbbs /etc/default
  sed -i 's#/data#/appdata#g' /appdata/default/photonbbs
fi

###
### Adjust the door scripts
###

cd /appdata/sbin
for script in *sh
do
  sed -i 's#export HOME="/opt/photonbbs"#export HOME="/appdata"#g' ${script} 2>/dev/null
done
cd -

chown -R bbs:bbs /appdata

###
### Intercept other commands.
###

if [ "$*" ]
then
  $*
  exit 0
fi

while [ true ]
do
  xinetd -dontfork
  sleep 1
done
