#!/usr/bin/perl
#
#  User manager for PhotonBBS
#  (C) 2009 Fewtarius
#  GNU GPL v2
#

$ppid = getppid;
if (-e "/etc/default/photonbbs") {
  open(my $cfg_fh, '<', "/etc/default/photonbbs");
  while (<$cfg_fh>) {
    $line=$_;
    chomp $line;
    ($key,$value)=split(/\=/,$line);
    $value=~s/^\"//;
    $value=~s/\".*$//;
    $config{$key}=$value;
  }
  close($cfg_fh);
} else {
  die "Please configure your BBS (/etc/default/photonbbs)";
}

require ($config{'home'}."/modules/pb-framework");
require ($config{'home'}."/modules/pb-usertools");

$|=1;

$node=@ARGV[1];
if (-e "$config{'doors'}/nodes/$node/fusiondoor") {
  open (my $fd_fh, '<', "$config{'doors'}/nodes/$node/fusiondoor");
  while (<$fd_fh>) {
    $instream=$_;
    chomp $instream;
    ($key,$value)=split(/\=/,$instream);
    $fusiondoor{$key}=$value;
  }
  close ($fd_fh);
  if ($fusiondoor{'security'} <= $config{'sysopsecurity'}) {
    die "You do not have permission to run this tool!";
  }
} else {
  $fusiondoor{'ansi'}=1;
}

$sysinfo{'os'} = $^O;
if ($sysinfo{'os'} =~/linux/) {
  $BSD_STYLE=1;
} elsif ($sysinfo{'os'} =~/hpux/) {
  $BSD_STYLE=0;
} else {
  $BSD_STYLE=1;
}

# Get TTY device path using POSIX
eval { require POSIX; $mytty = POSIX::ttyname(fileno(STDIN)); };
if (!$mytty) { chomp($mytty = `tty 2>/dev/null`); }

open(my $users_fh, '<', "$config{'home'}$config{'data'}/users.dat");
  while (<$users_fh>) {
    chomp;
    ($idx,$name)=split(/\|/,$_);
    push(@users,$name);
  }
close($users_fh);

applytheme($config{'theme'});
$sk=0;
for (;;) {
  $usridxcnt=scalar(@users);
  if ($sk < 0) {
    $sk=$usridxcnt;
    --$sk;
  } elsif ($sk >= $usridxcnt) {
    $sk=0;
  }

  loaduser($sk);
  if ($info{'ansi'} eq "0") {
    $ansi="Off";
  } else {
    $ansi="On";
  }

  $save{'ansi'}=$info{'ansi'};
  $save{'ext'}=$info{'ext'};

  $info{'ansi'}=$fusiondoor{'ansi'};
  if ($fusiondoor{'ansi'} eq "1") {
    $info{'ext'}="ans";
  } else {
    $info{'ext'}="asc";
  }
  colorize();

  if ($info{'dnd'} eq "0") {
    $dnd="Off";
  } else {
    $dnd="On";
  }

  print "\e[2J\e[0;0H";
  writeline ($config{'themecolor'}."User Editor - ".$config{'usercolor'}." [ ".$config{'systemcolor'}.($sk+1).$config{'usercolor'}."/".$config{'systemcolor'}.scalar(@users).$config{'usercolor'}." ]",1);
  writeline ("",1);
  writeline ("",1);
  writeline ($config{'datacolor'}."A. ".$config{'usercolor'}."Handle : ".$config{'systemcolor'}.$info{'handle'},1);
  writeline ($config{'datacolor'}."B. ".$config{'usercolor'}."Real Name : ".$config{'systemcolor'}.$info{'rname'},1);
  writeline ($config{'datacolor'}."C. ".$config{'usercolor'}."D.O.B. : ".$config{'systemcolor'}.$info{'dob'},1);
  writeline ($config{'datacolor'}."D. ".$config{'usercolor'}."Email Address : ".$config{'systemcolor'}.$info{'email'},1);
  writeline ($config{'datacolor'}."E. ".$config{'usercolor'}."Location : ".$config{'systemcolor'}.$info{'location'},1);
  writeline ("",1);
  writeline ($config{'datacolor'}."F. ".$config{'usercolor'}."Password : ".$config{'systemcolor'}."********",1);
  writeline ($config{'datacolor'}."G. ".$config{'usercolor'}."Security : ".$config{'systemcolor'}.$info{'security'},1);
  writeline ("",1);
  writeline ($config{'datacolor'}."H. ".$config{'usercolor'}."Ansi : ".$config{'systemcolor'}.$ansi,1);
  writeline ($config{'datacolor'}."I. ".$config{'usercolor'}."Do Not Disturb : ".$config{'systemcolor'}.$dnd,1);
  writeline ($config{'datacolor'}."J. ".$config{'usercolor'}."Hidden : ".$config{'systemcolor'}.$info{'hidden'},1);
  writeline ($config{'datacolor'}."K. ".$config{'usercolor'}."Theme : ".$config{'systemcolor'}.$info{'theme'},1);
  writeline ($config{'datacolor'}."L. ".$config{'usercolor'}."Default channel : ".$config{'systemcolor'}.$info{'defchan'},1);
  writeline ($config{'datacolor'}."M. ".$config{'usercolor'}."Account Banned : ".$config{'systemcolor'}.$info{'banned'},1);
  writeline ("",1);
  writeline ($config{'datacolor'}."[. ".$config{'usercolor'}."Previous User",1);
  writeline ($config{'datacolor'}."]. ".$config{'usercolor'}."Next User",1);
  writeline ($config{'themecolor'}."Enter Option, or \"".$config{'datacolor'}."Q".$config{'themecolor'}."\" to quit: ");

  $key="";
  cbreak(on);
  $key=waitkey();
  cbreak(off);

  writeline("",1);

  $info{'ansi'}=$save{'ansi'};
  $info{'ext'}=$save{'ext'};

  if ($key eq "[") {
    --$sk;
    next;
  } elsif ($key eq "]") {
    ++$sk;
    next;
  }
  if ($key =~/^[Qq]/) {
    writeline("$RST");
    exit 0;
  }

  if ($key =~/^[Aa]/) {
    chhandle();
    next;
  }

  if ($key =~/^[Bb]/) {
    chrealname();
    next;
  }

  if ($key =~/^[Cc]/) {
    chdob();
    next;
  }

  if ($key =~/^[Dd]/) {
    chemail();
    next;
  }

  if ($key =~/^[Ee]/) {
    chlocal();
    next;
  }

  if ($key =~/^[Ff]/) {
    chpassword();
    next;
  }

  if ($key =~/^[Gg]/) {
    chsecurity();
    next;
  }

  if ($key =~/^[Hh]/) {
    chansi();
    next;
  }

  if ($key =~/^[Ii]/) {
    chdnd();
    next;
  }

  if ($key =~/^[Jj]/) {
    #hide
  }

  if ($key =~/^[Kk]/) {
    chtheme();
    next;
  }

  if ($key =~/^[Ll]/) {
    chdefault();
    next;
  }

  if ($key =~/^[Mm]/) {
    chbanned();
    next;
  }

}

sub chtheme {
  opthe: {
    writeline($config{'themecolor'} . "Please enter a new theme to use: ");
    $info{'theme'} = getline(text, 20, "", 1);
    unless (-e $config{'home'} . $config{'themes'} . "/" . $info{'theme'}) {
      writeline($RED . "That theme does not exist, please choose another.", 1);
      goto opthe;
    }
  }
  updateuser();
}

sub chdefault {
  writeline($config{'themecolor'} . "Please enter a new default channel: ");
  $info{'defchan'} = getline(text, 20, "", 1);
  $info{'defchan'} = uc($info{'defchan'});
  $info{'defchan'} =~ s/\ /_/gi;
  updateuser();
}

sub chhandle {
  opnewid: {
    writeline($config{'themecolor'}."Please enter a new handle: ");
    $handle=getline(text,16,"",1);
    $handletest=uc($handle);
    if ($handletest =~/New/gi) {
      $test="valid";
    }
    $test=finduser($handle);
    unless ($test eq "valid") {
       $info{'handle'}=$handle;
       updateuser();
       alterindex();
    } else {
       writeline($RED."Sorry, that name is not available.",1);
       $test="";
       $handle="";
       $handletest="";
       goto opnewid;
    }
  }
}

sub chsecurity {
    opsec: {
    writeline($config{'themecolor'}."Please enter a new security level: ");
    $info{'security'}=getline(text,3,"",1);
    unless ($info{'security'} gt "0") {
      goto opsec;
    }
  }
  updateuser();
}

sub alterindex() {
  $userindex=$config{'home'}.$config{'data'}."/users.dat";
  lockfile("$userindex");
  open (my $idx_in, '<', $userindex);
    @records=<$idx_in>;
  close ($idx_in);

  open (my $idx_out, '>', $userindex);
    foreach $record(@records) {
      chomp $record;
      ($recid,$recname)=split(/\|/,$record);
      if ($recid eq $info{'id'}) {
        $recname=$info{'handle'};
      }
      print $idx_out "$recid|$recname\n";
    }
  close($idx_out);
  unlockfile("$userindex");
}
